---

- name: nginx config
  template: >
    src={{ item.type }}/project_v{{ item.version|default('2') }}.j2
    dest=/etc/nginx/sites-available/{{ item.name ~ (('_' ~ item.index) if (item.index|default('app') != 'app') else '') }}
  notify:
    - nginx restart
  with_items: elao_projects
  sudo: yes

- name: nginx enable
  shell: >
    ngxensite {{ item.name ~ (('_' ~ item.index) if (item.index|default('app') != 'app') else '') }}
    creates=/etc/nginx/sites-enabled/{{ item.name ~ (('_' ~ item.index) if (item.index|default('app') != 'app') else '') }}
  notify:
    - nginx restart
  with_items: elao_projects
  sudo: yes

- name: nginx default disable
  file: >
    dest=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - nginx restart
  sudo: yes

- name: root symfony
  file: >
    path={{ item.root|default('/srv/' ~ item.name ~ '/symfony') }}
    state=directory
    owner={{ item.user|default(elao_base_user) }}
    group={{ item.group|default(elao_base_group) }}
  with_items: elao_projects
  when: item.type == 'symfony' and not elao_vagrant
  sudo: yes

- name: root silex
  file: >
    path={{ item.root|default('/srv/' ~ item.name ~ '/silex') }}
    state=directory
    owner={{ item.user|default(elao_base_user) }}
    group={{ item.group|default(elao_base_group) }}
  with_items: elao_projects
  when: item.type == 'silex' and not elao_vagrant
  sudo: yes

- name: cache symfony
  file: >
    path={{ item.cache|default('/srv/' ~ item.name ~ '/cache') }}
    state=directory
  with_items: elao_projects
  when: item.type == 'symfony' and elao_vagrant
  sudo: yes

- name: logs symfony
  file: >
    path={{ item.logs|default('/srv/' ~ item.name ~ '/logs') }}
    state=directory
  with_items: elao_projects
  when: item.type == 'symfony' and elao_vagrant
  sudo: yes

- name: acl symfony
  shell: >
    setfacl -R -m u:{{ elao_nginx_user }}:rwX -m u:{{ item.user|default(elao_base_user) }}:rwX {{ item.cache|default('/srv/' ~ item.name ~ '/cache') }} {{ item.logs|default('/srv/' ~ item.name ~ '/logs') }}
  with_items: elao_projects
  when: item.type == 'symfony' and elao_vagrant
  sudo: yes

- name: acl default symfony
  shell: >
    setfacl -dR -m u:{{ elao_nginx_user }}:rwx -m u:{{ item.user|default(elao_base_user) }}:rwx {{ item.cache|default('/srv/' ~ item.name ~ '/cache') }} {{ item.logs|default('/srv/' ~ item.name ~ '/logs') }}
  with_items: elao_projects
  when: item.type == 'symfony' and elao_vagrant
  sudo: yes
