---

- name: project nginx config
  template: >
    src={{ item.value['type'] }}/project.j2
    dest=/etc/nginx/sites-available/{{ item.key }}
  notify:
    - nginx restart
  with_dict: elao_projects
  sudo: yes

- name: project nginx enable
  shell: >
    ngxensite {{ item.key }}
    creates=/etc/nginx/sites-enabled/{{ item.key }}
  notify:
    - nginx restart
  with_dict: elao_projects
  sudo: yes

- name: project permission
  file: >
    path={{ item.value['root']|default('/srv/' ~ item.key ~ '/symfony') }}
    state=directory
    owner={{ item.value['user']|default(elao_base_user) }}
    group={{ item.value['group']|default(elao_base_group) }}
  with_dict: elao_projects
  when: item.value['type'] == 'symfony' and not elao_vagrant
  sudo: yes

- name: project symfony cache
  file: >
    path={{ item.value['cache']|default('/srv/' ~ item.key ~ '/cache') }}
    state=directory
  with_dict: elao_projects
  when: item.value['type'] == 'symfony' and elao_vagrant
  sudo: yes

- name: project symfony logs
  file: >
    path={{ item.value['logs']|default('/srv/' ~ item.key ~ '/logs') }}
    state=directory
  with_dict: elao_projects
  when: item.value['type'] == 'symfony' and elao_vagrant
  sudo: yes

- name: project acl
  shell: >
    setfacl -R -m u:{{ elao_nginx_user }}:rwX -m u:{{ item.value['user']|default(elao_base_user) }}:rwX {{ item.value['cache']|default('/srv/' ~ item.key ~ '/cache') }} {{ item.value['logs']|default('/srv/' ~ item.key ~ '/logs') }}
  with_dict: elao_projects
  when: item.value['type'] == 'symfony' and elao_vagrant
  sudo: yes

- name: project acl default
  shell: >
    setfacl -dR -m u:{{ elao_nginx_user }}:rwx -m u:{{ item.value['user']|default(elao_base_user) }}:rwx {{ item.value['cache']|default('/srv/' ~ item.key ~ '/cache') }} {{ item.value['logs']|default('/srv/' ~ item.key ~ '/logs') }}
  with_dict: elao_projects
  when: item.value['type'] == 'symfony' and elao_vagrant
  sudo: yes
